#!/usr/bin/env bash -eu

readonly result=$(zle/lib/command-exchange "SOME_VAR=some view some_file" "vim")

readonly expected="SOME_VAR=some vim some_file"

if [ "$result" = "$expected" ]; then
  echo [OK]
  echo "(Got)" "$result"
  echo "(Exp)" "$expected"
else
  echo [NG]
  echo "(Got)" "$result"
  echo "(Exp)" "$expected"
  exit 1
fi
