#!/usr/bin/env zsh -eu

_command_exchange () {
  BUFFER=$(echo "$BUFFER" | perl -pe "s/(^|\s+)([a-z][a-z0-9]+\s+)/ /")
  CURSOR=0
}

zle -N command-exchange _command_exchange

# Recipi
# bindkey "^W^E" command-exchange

