#!/usr/bin/env zsh -eu

incremental-select-command-history() {
   if [ ! $(which peco) ]; then echo "You need peco" && exit 1; fi

   local original_buffer="$BUFFER"

   fc -R

   if [ ! -z $(peco --help | grep '\--print-query') ]; then
     local peco_print_query='--print-query'
   else
     local peco_print_query=''
   fi

   BUFFER=$( \
      history 1 | \
      sort -k1,1nr | \
      perl -ne 'BEGIN { my @lines = (); } s/^\s*\d+\*?\s*//; $in=$_; if (!(grep {$in eq $_} @lines)) { push(@lines, $in); print $in; }' | \
      peco --layout=bottom-up --on-cancel=error "$peco_print_query"
   )

   zle reset-prompt

   # Keep original input when escape from select
   if [ -z "$BUFFER" ]; then
     BUFFER="$original_buffer"
   fi

   CURSOR=${#BUFFER}
}

zle -N incremental-select-command-history

# Recipi
# bindkey '^[[A' incremental-select-command-history

