#!/usr/bin/env zsh -eu

peco-select-history-up() {
  fc -R

  BUFFER=$(history 1 | sort -k1,1nr | perl -ne 'BEGIN { my @lines = (); } s/^\s*\d+\*?\s*//; $in=$_; if (!(grep {$in eq $_} @lines)) { push(@lines, $in); print $in; }' | peco --query="$LBUFFER")

  CURSOR=${#BUFFER}
  zle reset-prompt
}

zle -N peco-select-history-up

# Recipi
# bindkey '^R' peco-select-history-up

